### ISSUE TITLE
Plagiarism and copying original code without giving credit

### ISSUE THREAD

**Issue by bigman73** [ArSn/jay-gee-eff-for-web#1]
The jay-gee-eff project was created by me well before the jay-gee-eff-for-web was created.
https://github.com/bigman73/jay-gee-eff

jay-gee-eff-for-web is a copy of the idea, source code and even shameless copy of the example code (NBA) without mentioning or giving any credit to the original jay-gee-eff project

**Comment by ArSn** [comment]
@bigman73 Sorry for getting back to you so late on this. Apprently I missed the github notification. It is not entirely true that I am not giving any credit, see here: https://github.com/ArSn/jay-gee-eff-for-web/blob/master/package.json#L25

As a matter of fact I started out reusing your code but in the end wrote everything from scratch. Granted your commits are still in the history and the NBA example is taken over. 

Now my intention was never to step on any toes and I gladly admit that the idea came from your package, mine now just does something entirely different. 

In what way would you best like me to state that somewhere in the code? Or which other measures could I take to your satisfaction? Terribly sorry if we got off on the wrong foot.

**Comment by bigman73** [comment]
Hi,
Thanks for getting back to me.

I have no problem with you forking or cloning the the project and logic.
My only frustration was that the it was not obvious where the original work came from.
I didn't notice your package.json. 
It is often acceptable to provide credits in README.md and/or a CREDITS file.
README.md is a much more visible place that shows up both on github and npm.

**Comment by ArSn** [comment]
@bigman73 Would you be happy with the note that I added in the linked pull request? :)

**Comment by bigman73** [comment]
Issue resolved, thank you
